<link rel="stylesheet" href="../../styles/theme_style.css">
<!--link rel="stylesheet" href="../../styles/header_style.css"-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<table width="100%">
    <tr>
        <td id="image_td" width="15%" class="header_image_color_1"><div id="image_img"
        class="header_image_1"></div></td>
        <td class="header_text">Load acquired data from .txt file</td>
    </tr>
</table>

<div id="flex-container">
    <div id="diff_level" class="flex-item">
        <strong>Difficulty Level:</strong>   <span class="fa fa-star checked"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
    </div>
    <div id="tag" class="flex-item-tag">
        <span id="tag_list">
            <table id="tag_list_table">
                <tr>
                    <td class="shield_left">Tags</td>
                    <td class="shield_right" id="tags">open&#9729;load&#9729;txt</td>
                </tr>
            </table>
        </span>
        <!-- [OR] Visit https://img.shields.io in order to create a tag badge-->
    </div>
</div>


A text file is one of the simplest means to store information, being a format outputted by **<span class="color2">OpenSignals</span>**.

In this **<span class="color5">Jupyter Notebook</span>** it will be explained how to load/transpose the data inside .txt file to a **<span class="color1">Python</span>** list, which consists in a step that precedes all processing operations.


<hr>

<p class="steps">1 - Importation of the needed packages</p>

In [1]:
# Package used for loading data from the input text file
from numpy import loadtxt

# biosignalsnotebooks python package
import biosignalsnotebooks as bsnb

<p class="steps">2 - Access to electrophysiological signals list</p>

<p class="steps">2.1 - Enter <i><span class="color2">biosignalsplux</span></i> url</p>

<img src="../../images/open/biosignalsplux_link.png">

<p class="steps">2.2 - Navigate through <i><span class="color2">biosignalsplux</span></i> main page menu and enter in "Signal Samples" page</p>

<img src="../../images/open/signal_samples_link.png">

<p class="steps">2.3 - Interactive buttons for accessing each signal sample file</p>

<img src="../../images/open/signal_samples_file_link.png">

<p class="steps">2.4 - File url copy (right-click of the mouse in the desired signal file icon)</p>

<img src="../../images/open/copy_link.png">

In [2]:
copy_link = 'https://www.biosignalsplux.com/downloads/samples/sensor_samples/biosignalsplux_Electrodermal_Activity_EDA_Sample.txt'

<p class="steps">3 - Get file from URL (<a href="http://biosignalsplux.com/downloads/samples/sensor_samples/biosignalsplux_Blood_Volume_Pulse_(BVP)_Sample.txt">http://biosignalsplux.com/downloads/samples/sensor_samples/biosignalsplux_Blood_Volume_Pulse_(BVP)_Sample.txt</a>)</p>

In [3]:
# File download.
bsnb.download(copy_link, out="download_file_name.txt")

<p class="steps">4 - Transposition of data to a Python list</p>

In [4]:
data = loadtxt("download_file_name.txt")

<p class="steps">5 - Identification of acquisition sampling rate in the file header ("sampling rate" key)</p>

In [5]:
# Embedding of .pdf file
from IPython.display import IFrame
IFrame(src="https://biosignalsplux.com/downloads/samples/sensor_samples/biosignalsplux_Blood_Volume_Pulse_(BVP)_Sample.txt", width="100%", height="350")

<img src="../../images/open/file_header_sampling_rate.png">

In [6]:
sampling_rate = 1000

<p class="steps">6 - Generation of time axis for signal plotting</p>

In [7]:
time = bsnb.generate_time(data, sampling_rate)

<p class="steps">7 - Final Output of the loaded data</p>

In [8]:
print (data)

[[0.0000e+00 0.0000e+00 4.6888e+04]
 [1.0000e+00 0.0000e+00 4.6958e+04]
 [2.0000e+00 0.0000e+00 4.6872e+04]
 ...
 [2.8170e+03 0.0000e+00 3.6728e+04]
 [2.8180e+03 0.0000e+00 3.6773e+04]
 [2.8190e+03 0.0000e+00 3.6737e+04]]


Each line of the list defines a sample acquired at a specific time instant and each column can be the sample number (*nSeq* ), digital input (*DI* ) or a sample value (*CH1* ), like described in the file header bellow.

In [9]:
# Embedding of .pdf file
from IPython.display import IFrame
IFrame(src="https://biosignalsplux.com/downloads/samples/sensor_samples/biosignalsplux_Blood_Volume_Pulse_(BVP)_Sample.txt", width="100%", height="350")

<img src="../../images/open/file_header_columns.png">

The samples of the signal under analysis are stored at the third entry of each list element (index 2).

In [10]:
channel_column = 2

<p class="steps">8 - Graphical representation of the signal (raw data)</p>

In [11]:
bsnb.plot(time, data[:, channel_column])

<i>This procedure can be automatically done by <strong>load</strong> function of <strong><span class="color2">biosignalsnotebooks</span></strong> package</i>

Text files are very popular and, like the name suggests, almost all type of contents can be stored here if they can be translated into a text format.

Numpy <strong>loadtxt</strong> function is very simple and efficient, so, it can be used even for text files not returned by <span class="color2">OpenSignals</span>.

<strong><span class="color7">We hope that you have enjoyed this guide. </span><span class="color2">biosignalsnotebooks</span><span class="color4"> is an environment in continuous expansion, so don't stop your journey and learn more with the remaining <a href="../MainFiles/biosignalsnotebooks.ipynb">Notebooks <img src="../../images/icons/link.png" width="10px" height="10px" style="display:inline"></a></span></strong> ! 

<span class="color6">**Auxiliary Code Segment (should not be replicated by
the user)**</span>

In [12]:
from biosignalsnotebooks.__notebook_support__ import css_style_apply
css_style_apply()

.................... CSS Style Applied to Jupyter Notebook .........................


In [13]:
%%html
<script>
    // AUTORUN ALL CELLS ON NOTEBOOK-LOAD!
    require(
        ['base/js/namespace', 'jquery'], 
        function(jupyter, $) {
            $(jupyter.events).on("kernel_ready.Kernel", function () {
                console.log("Auto-running all cells-below...");
                jupyter.actions.call('jupyter-notebook:run-all-cells-below');
                jupyter.actions.call('jupyter-notebook:save-notebook');
            });
        }
    );
</script>